### ISSUE TITLE
Cannot import nodes

### ISSUE THREAD

**Issue by grinlau18** [pythongosssss/ComfyUI-Custom-Scripts#52]
Hello author, the following problem occurred during installation and operation. How can I solve it?
However, this issue does not occur when using ComfyUI Revision: 1218
——————
### ComfyUI Revision: 1338 [e3d0a9a4]
Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/__init__.py", line 12, in <module>
    files = glob.glob("*.py", root_dir=py, recursive=False)
TypeError: glob() got an unexpected keyword argument 'root_dir'

Cannot import /root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts module for custom nodes: glob() got an unexpected keyword argument 'root_dir'

**Comment by pythongosssss** [comment]
Hi, this is due to using an order version of python (pre 3.10)
I've updated this so it should now work on 3.9, but I would recommend you upgrade to 3.10 if possible!

**Comment by grinlau18** [comment]
I understand. Thank you for your answer：）
